### ISSUE TITLE
telegram app 貌似不能用

### ISSUE THREAD

**Issue by OxygenLiu** [h2y/Shadowrocket-ADBlock-Rules#1]
需要设置什么rule?

**Comment by h2y** [comment]
专门下载个电报 App 来测试，发现 telegram 使用的是 IP 与服务器进行连接，而不是域名。

需要的规则是：`IP-CIDR,91.108.56.0/22,Proxy`，但是 SR 尽然不支持，在这条规则下仍然走直连，已经将这个问题反馈给了 SR 作者，等待回复中。

目前而言将 Global Routing 设置为 Proxy 是可以正常使用 telegram 的。

**Comment by yangxiaoge** [comment]
亲测 telegram 也不能用, Proxy 可以正常使用.

**Comment by gohki** [comment]
telegram好像还有其他IP段，刚才开sr的log看到了91.108.56.165和149.154.167.91。
暂时把FINAL改成PROXY了……

**Comment by DrayChou** [comment]
测试了下， telegram 是不能用的。
不过， http://www.abclite.cn/2311.html 这边的规则是可以用的。

**Comment by h2y** [comment]
关于 Telegram 已进行更新：<https://github.com/h2y/Shadowrocket-ADBlock-Rules/commit/56c6793b94b32f3cf9824638dac9174daf0f5c42>（不过我本人未测试）
请大家重新下载并激活一次规则文件。
