### ISSUE TITLE
「黑名单过滤 + 广告」模式不支持 Telegram

### ISSUE THREAD

**Issue by f2sky** [h2y/Shadowrocket-ADBlock-Rules#105]
1）对应规则：
黑名单过滤 + 广告
黑名单中包含了境外网站中无法访问的那些，对不确定的网站则默认直连。

代理：被墙的网站（GFWList）
直连：正常的网站
包含广告过滤
规则地址：https://raw.githubusercontent.com/h2y/Shadowrocket-ADBlock-Rules/master/sr_top500_banlist_ad.conf

2）问题描述
直接用规则不能打开 Telegram 消息，开启「全局模式」模式则正常收发消息。

**Comment by h2y** [comment]
已确认此问题，是 GFWList 的遗漏，已提交至上游：
<https://github.com/gfwlist/gfwlist/issues/1067>

**Comment by cnfanhua** [comment]
请问、问题还没解决吗
