### ISSUE TITLE
使用规则的授权请求

### ISSUE THREAD

**Issue by ToutyRater** [h2y/Shadowrocket-ADBlock-Rules#106]
你好，首先很感谢你提供的规则，令许多人都有良好的上网体验。我是 [V2Ray 白话文教程](https://toutyrater.github.io)的作者ToutyRater，[V2Ray](https://v2ray.com) 是另外一种与 Shadowsocks 有些类似的上网工具，它内置了一个[策略路由](https://v2ray.com/chapter_02/03_routing.html)的功能，可以通过一定的策略将数据包进行拦截、绕过代理或者转发到指定的代理。由于目前还没有人分享有适合 V2Ray 使用的规则，所以我想做这样一个工作。有句话说不要重复造轮子，何况是这么好的轮子。因此我想向你请求授权，可以允许我使用你的规则文件修改成适用于 V2Ray 的格式。

**Comment by h2y** [comment]
好的呀。
可以的话欢迎修改本项目的 Python 代码来实现自动生成 V2Ray 规则。
本项目后期有计划生成除了 SR 之外的其他规则。

**Comment by ToutyRater** [comment]
多谢！如果有余力会考虑你的建议的。
