### ISSUE TITLE
google voice 不在黑名单中

### ISSUE THREAD

**Issue by XueyangXu** [h2y/Shadowrocket-ADBlock-Rules#112]
我用hongouts拨打电话，全局代理下能打通能说话，在规则代理下，对方能被呼叫但是对方一接起来，我这里就会呼叫失败，我看了日志有两个连接 stun.l.google.com:19302和74.125.23.127:19305 类型是udp

**Comment by XueyangXu** [comment]
测试了只要添加74.125.23.127/32这条规则即可

**Comment by h2y** [comment]
这条规则目前是有的，建议更新一下规则文件。

**Comment by XueyangXu** [comment]
我很确信我更新top500+黑名单后，74.125.23.127/32还是直连的。

**Comment by h2y** [comment]
已添加
