### ISSUE TITLE
国内网络下直连去广告无法访问美区APP STORE

### ISSUE THREAD

**Issue by huangfengye** [h2y/Shadowrocket-ADBlock-Rules#115]
国内网络下直连去广告无法访问美区APP STORE

**Comment by h2y** [comment]
我这里使用国区 ID 访问美区 Store 是可以的，建议你打开日志功能，查看下是哪条规则导致的拒绝连接，然后反馈给我。

**Comment by huangfengye** [comment]
https://www.youtube.com/edit?o=U&video_id=Y211wazA2bI

**Comment by huangfengye** [comment]
已经知道是什么问题了。。。IOS12 beta4的BUG，VPN环境下无法进入APP STORE...
