### ISSUE TITLE
导入二维码之后，解码时间需要多久啊

### ISSUE THREAD

**Issue by jessyyoungj** [h2y/Shadowrocket-ADBlock-Rules#118]
导入shadowrocket国内外划分 + 广告二维码添加配置，界面一直显示“正在解码”。花了一个晚上的时间还是没有解码完成，请问导入二维码的时间大概是要多久，导入之后直接点击“使用配置”是吗。急急急！

**Comment by h2y** [comment]
这，，应该是一瞬间就完成的，就和平时扫描二维码一样。
注意是在配置里面添加二维码，而不是在节点里面扫描二维码

**Comment by jessyyoungj** [comment]
感谢，不能保存图片识别，只能直接扫描，了解了解！！
但是连接之后shadowrocket重新连接，Facebook显示"未能文成该操作AsyncSocketException:Network error,type=Network error.”
我应该调整哪里呢？全局路由那里选择“配置”是吗

**Comment by h2y** [comment]
是的，全局路由那里选择 “配置”

**Comment by jessyyoungj** [comment]
延迟测试是有速度显示的，但还是不能翻墙，请问是什么原因呢？我需要把设置的截图发你吗

**Comment by jessyyoungj** [comment]
在 ShadowRocket 应用中，进入 [配置] 页面，点击扫描二维码的按钮添加规则。再激活添加的规则文件即可。
这里说的激活就是选择“使用配置”是吗

**Comment by h2y** [comment]
是的，选择“使用配置”。
你可以先试试全局路由那里选择“代理”，如果还是无法翻墙，那就和规则无关了，是你的节点有问题。

可以试试糖客提供的节点：<http://tangke.party/register?aff=56>

**Comment by jessyyoungj** [comment]
我的节点在PC端是可以使用的，就是在手机端不能使用，实在是想破脑袋，不知道是什么原因，是不是哪个地方需要调整？？

**Comment by h2y** [comment]
你这我也不太清楚，你先试试糖客派对的节点 <https://tangke.party> 看下是不是节点的原因。
