### ISSUE TITLE
「全局直连 + 去广告」会屏蔽 Google 搜索

### ISSUE THREAD

**Issue by adxsin** [h2y/Shadowrocket-ADBlock-Rules#121]
「全局直连 + 去广告」会屏蔽 Google 搜索，应该是屏蔽广告相关站点，Google 搜索似乎也被屏蔽掉了

**Comment by h2y** [comment]
全局直连是不带翻墙功能的。

**Comment by adxsin** [comment]
问题是我本身就在墙外不需要翻。我下了最新的版本，好像又OK了。
