### ISSUE TITLE
“国内外划分”配置文件相关

### ISSUE THREAD

**Issue by B4Ev** [h2y/Shadowrocket-ADBlock-Rules#122]
谢谢h2y提供的方便。有一个问题就是当我使用“国内外划分”（去不去广告的都是）配置文件时，利用safari浏览器打开“www.google.com”域名时会自动跳转到百度的“未找到网页”error界面。尝试更换dns，清除缓存仍然无法解决，但地址栏里输入搜索内容仍然可以提供google的搜索引擎建议。此外，更换其他浏览器时该问题消失，GFWList配置文件使用时也未出现此问题。谢谢。

**Comment by debug1996** [comment]
使用safari 和 夸克浏览器 访问google.com均出现404 访问https://www.google.com.hk/却可以 不知道啥情况

**Comment by h2y** [comment]
我这里测试没有这个问题，“国内外划分” 配置文件用的是 geoIP 判断国内外，如果有问题建议更新一下 SR App。
