### ISSUE TITLE
添加规则

### ISSUE THREAD

**Issue by lonelykid** [h2y/Shadowrocket-ADBlock-Rules#129]
希望在手动选项里加上这些。
umeng.co
umeng.com
umengcloud.com
easylist china里面其实也是有的，不过是css selector，直接pass了。
当然直接把script改一改，把pass掉的加上可能更好。

**Comment by h2y** [comment]
友盟是一家给站长用的网站，虽然可以屏蔽掉根域实现相关统计脚本的屏蔽，但是其主页也就不能正常打开了。
这也是 easylist china 没有对根域屏蔽的原因。

**Comment by lonelykid** [comment]
并不只是统计脚本，还有非常烦人的广告。至于连带网站也屏蔽掉，我就不知道有什么好办法了。
