### ISSUE TITLE
feedly 已被墙

### ISSUE THREAD

**Issue by OceanApart** [h2y/Shadowrocket-ADBlock-Rules#132]
Feedly 的主页 `https://feedly.com` 可以直连，但是其他子域名已经被墙。例如：使用 Reeder 已经不能正常同步内容。
请修改原有规则 `DOMAIN-SUFFIX,feedly.com,Direct` 为 `DOMAIN-SUFFIX,feedly.com,Proxy`

**Comment by kid1412621** [comment]
官网都不能直连了

**Comment by tcbywing** [comment]
建议加入DOMAIN-SUFFIX,feedly.com,Proxy

**Comment by h2y** [comment]
我这里测试网页版的 feedly，不翻墙是可以正常阅读的。不过大家这么反馈，那就改成 Proxy 好了~
