### ISSUE TITLE
公司app接口域名被广告屏蔽拦截，请求解除

### ISSUE THREAD

**Issue by power12317** [h2y/Shadowrocket-ADBlock-Rules#138]
最近同事测试发现只要开了Shadowrocket就应用无法上网，不能进行正常的应用使用，发现是应用了这里广告屏蔽规则，直接屏蔽了整个主域名。
这几个域名已经有很长一段历史了，从别的公司转过来的，应该是以前的公司使用这些域名做了横幅漂浮广告被加入了屏蔽列表一直持续到现在的。
现在的公司并没有漂浮悬浮广告业务，应该不会对正常浏览其他网站的用户造成影响，加上最近启用这几个域名作为公司一些app的接口，已经推广出去了暂时没办法立即更换，所以请求解除屏蔽。
由于域名解析权不在我这， 没办法知道公司是否还会用这些域名的子域名去做广告推广，如果还是有收到用户的广告投诉麻烦屏蔽掉对应的二级域名，不要屏蔽主域名，谢谢！

涉及域名：
```
niudashu.com
beigedi.com
xiongdong.com

```

**Comment by h2y** [comment]
确实有对这几个域名主域名的屏蔽，建议向 easylistchina 和 xinggsf/Adblock-Plus-Rule 反馈，这里是拉取的他们的广告列表。
