### ISSUE TITLE
关于白名单sr_top500_whitelist.conf，无法打开手机维基百科页面

### ISSUE THREAD

**Issue by ntgeralt** [h2y/Shadowrocket-ADBlock-Rules#142]
你好，我最近用sr_top500_whitelist.conf模式，在小火箭发现个问题：重现方式如下：
sr_top500_whitelist.conf规则下手机打开google.com，搜索‘向日葵 维基百科’，出结果后，第一条是向日葵的维基百科。点击第一条，出现卡在无法跳转到维基百科的状态。上面菊花一直在转……

这时候小火箭由‘配置’改成代理。全局代理后，点击维基百科的搜索结果则能正常跳转。烦请你看看

**Comment by Arrow-C** [comment]
我也出现了这个问题，不止维基，我有时连Google也打不开

**Comment by arslan2012** [comment]
对，白名单里面有非常多的错误，wikipedia.com, imgur.com等很多被墙了的网站都在白名单里面

**Comment by h2y** [comment]
建议更新一下白名单，我这里测试谷歌和维基都是没有问题的。

**Comment by ntgeralt** [comment]
can work now.
