### ISSUE TITLE
Twitch无法加载聊天室

### ISSUE THREAD

**Issue by lcysyx** [h2y/Shadowrocket-ADBlock-Rules#147]
使用“国内外划分 + 广告”规则时，Twitch应用中无法加载聊天室

**Comment by lcysyx** [comment]
经测试不使用去广告规则仅使用“国内外划分”也无法加载聊天内容。全局代理的情况下可以加载聊天内容。应该是“国内外划分”规则让Twitch的聊天走了直连。

**Comment by h2y** [comment]
希望能提交一下 Twitch 的域名和 ip
