### ISSUE TITLE
全局直连去广告【sr_direct_banad.conf】对百度贴吧APP无效

### ISSUE THREAD

**Issue by wwmbao** [h2y/Shadowrocket-ADBlock-Rules#150]
- 系统：IOS 12
- 软件：shadowrocket 2.1.11、百度贴吧 9.9.9
- 规则地址：https://raw.githubusercontent.com/h2y/Shadowrocket-ADBlock-Rules/master/sr_direct_banad.conf

- 问题：开启VPN并使用此配置文件后，打开百度贴吧APP依然能在看贴时看见广告

**Comment by h2y** [comment]
已记录，去广告只能慢慢地适配了
