### ISSUE TITLE
虾米app在使用回国规则时，会显示地区限制

### ISSUE THREAD

**Issue by starsasdust** [h2y/Shadowrocket-ADBlock-Rules#152]
您好：

客户端：shadowrocket ios
虾米客户端：虾米7.5.8 ios
服务器所在地：菲力宾
使用配置版本：回国规则 + 广告
问题描述：
使用全局代理时，在客户端内，每日30首可以无版权限制听取
使用回国规则时，在客户端听每日30首，会显示：因版权保护，您所在的国家。。。。。

非常感谢

**Comment by starsasdust** [comment]
测试了单纯回国规则不含去广告，也会显示同样问题

**Comment by h2y** [comment]
这应该是因为你的代理服务器在菲律宾，而菲律宾本身是不能使用虾米的。
（回国规则应该搭配代理服务器在境内来使用）
