### ISSUE TITLE
Line不能发送消息

### ISSUE THREAD

**Issue by liu870825yi** [h2y/Shadowrocket-ADBlock-Rules#155]
Line用黑名单的规则表没办法发送信息

**Comment by yaozhisheng** [comment]
用白名单可以 可是白名单维基百科中文又不行 所以我的做法是用白名单 然后删除了wikip的两条 让他走代理 希望能帮到你 我不限流量，哥们自己看着办

**Comment by h2y** [comment]
希望能反馈一下是遗漏了哪个服务器地址

**Comment by h2y** [comment]
无反馈暂时关闭
