### ISSUE TITLE
使用国内外划分配置时无法使用Google

### ISSUE THREAD

**Issue by Arrow-C** [h2y/Shadowrocket-ADBlock-Rules#158]
问题如题，原因未知，使用国内外划分有无白名单结果一致，使用黑名单代理时不会出现该问题

**Comment by h2y** [comment]
我这里测试是正常的

**Comment by w316525096** [comment]
> 
> 
> 我这里测试是正常的

iOS12,
shadowrocket version : 2.1.53(998)
" 国内外划分"配置,无法连接google.com;  twitch网页; twitch app.
