### ISSUE TITLE
回国规则无效

### ISSUE THREAD

**Issue by yn3010** [h2y/Shadowrocket-ADBlock-Rules#162]
测试两种回国规则均无效
配置为全局模式时测试地址music.163.com有效访问，证明目标服务器正常

**Comment by yn3010** [comment]
看了下是规则里没music.163.com，建议添加，欧盟地区还是很需要的，手动添加后测试正常

**Comment by yn3010** [comment]
我看了下回国规则里把domain-suffix的.cn改成cn后比较正常

**Comment by h2y** [comment]
已修改，谢谢反馈
