### ISSUE TITLE
报出无效URL

### ISSUE THREAD

**Issue by to686312** [h2y/Shadowrocket-ADBlock-Rules#163]
我下载好shadowrocket  扫二维码报  无效url

**Comment by h2y** [comment]
你需要在规则页面扫码，不能在节点页面扫码

**Comment by to686312** [comment]
我在 shadowrocket 中得配置界面扫码马上 换上了 远程文件得conf  怎么没法访问谷歌  同时通知栏上没有 vpn得字样
