### ISSUE TITLE
系统服务器

### ISSUE THREAD

**Issue by NLasagna** [h2y/Shadowrocket-ADBlock-Rules#165]
请问黑名单是否【未收录】iOS 备份等的各种系统用服务器？换言之晚上能否不关闭 SSR 任其联网而不减速/跑梯子流量？

新手不知道怎么评论，只能 issue 了抱歉。

**Comment by h2y** [comment]
你好，收录了的。
我们的目标就是不关闭 SSR 任其联网而不减速 / 跑梯子流量。
