### ISSUE TITLE
目前无法屏蔽广告的APP

### ISSUE THREAD

**Issue by solologo** [h2y/Shadowrocket-ADBlock-Rules#169]
12306
网易考拉

**Comment by zhanghanqings** [comment]
IOS 应用：百度贴吧、今日头条
今日头条中有友盟的第三方接口，获取了用户的设备信息并上传，还有京东的接口，建议可以加入拒绝列表。

**Comment by h2y** [comment]
希望能提交一下这些广告App的地址。

**Comment by chingov** [comment]
IOS应用：hupu ，广告真是太恶心了。

**Comment by moerfutin** [comment]
http://kikibt8.com/   http://kikibt8.xyz/  这个域名的广告毒瘤，每隔段时间都会更好嵌入的脚本域名啊，头疼

Chingow <notifications@github.com> 于2019年7月7日周日 下午11:08写道：

**Comment by solologo** [comment]
> 希望能提交一下这些广告App的地址。

是app的下载地址，还是广告用到的域名啊？

**Comment by chingov** [comment]
> 希望能提交一下这些广告App的地址。

http://adx.hupu.com

**Comment by nictse2013** [comment]
IOS app：youtube  开头和中间都有广告，希望支持下

**Comment by solologo** [comment]
> 希望能提交一下这些广告App的地址。
网易考拉 https://apps.apple.com/cn/app/wang-yi-kao-la-hai-gou-quan/id965789238
微博国际版 http://itunes.apple.com/cn/app/%E5%BE%AE%E5%8D%9A%E5%9B%BD%E9%99%85%E7%89%88/id1215210046?mt=8

**Comment by h2y** [comment]
adx.hupu.com
kikibt8.com
kikibt8.xyz
现在已添加这三个广告域名。
