### ISSUE TITLE
youtube的片头广告无法屏蔽

### ISSUE THREAD

**Issue by heckles** [h2y/Shadowrocket-ADBlock-Rules#170]

**Comment by yezixi** [comment]
同样问题.出现这个问题很久了,原来都在电脑看YouTube就没管,前面试了一下还是不行,广告无法屏蔽导致一直转圈无法正常播放视频,切换到没有去广告的规则也一样,切到系统自带规则或开全局才能解决.

**Comment by yezixi** [comment]
补充:以上问题国内外划分不能用,在黑白名单规则下可以正常访问

**Comment by h2y** [comment]
油管的广告之前研究过，必须使用正则才能屏蔽，会卡网所以没有添加。
