### ISSUE TITLE
请问这个规则在android下如何添加？

### ISSUE THREAD

**Issue by justincnn** [h2y/Shadowrocket-ADBlock-Rules#173]
直接放在自定义规则下面发现都无法上网了

**Comment by cooper1x** [comment]
同问

**Comment by MoLan233** [comment]
这是Shadowrocket用的，Android用ACL https://github.com/ACL4SSR/ACL4SSR

**Comment by h2y** [comment]
这是用于iOS客户端的规则。

**Comment by cooper1x** [comment]
> 这是Shadowrocket用的，Android用ACL https://github.com/ACL4SSR/ACL4SSR

@MoLan233 V2ray可以用吗？安卓版的
