### ISSUE TITLE
WSJ 黑名单无法访问

### ISSUE THREAD

**Issue by NLasagna** [h2y/Shadowrocket-ADBlock-Rules#175]
黑名单没有包含华尔街邮报。

**Comment by NLasagna** [comment]
我测试了几次，不稳定，难以判断，请大家协助我测试。测试前记得更新远程文件。尽早关闭 Issue。

**Comment by NLasagna** [comment]
bartender.dowjones.com

此域名需要被添加为 PROXY。本 Issue 针对 WSJ iOS App 遇到的问题，Web 问题没有关注

**Comment by h2y** [comment]
已修改，谢谢反馈 :D

**Comment by NLasagna** [comment]
更新了文件并没有收录 bartender.dowjones.com 啊
