### ISSUE TITLE
iOSsafari搜索引擎谷歌无法使用

### ISSUE THREAD

**Issue by LLLLLFish** [h2y/Shadowrocket-ADBlock-Rules#176]
5.19配置版本，谷歌可以正常访问，safari谷歌搜索引擎就上不了

**Comment by LLLLLFish** [comment]
把类型改成302又可以了

**Comment by LeonSparta** [comment]
所以为什么把header改成302就又可以了啊，我排错排了一个多个小时发现了这个问题。所以我很好奇，shadowrocket中这两种重定向规则是怎么弄的啊，可以给我讲一一下吗，我很好奇。

**Comment by LeonSparta** [comment]
而且我同学的iPhone和我的iPad也可以，都还是 header规则。很奇怪啊。这个失效就是因为重定向失败了之类的？我也不知道，不是搞网络的，但是至少每次访问失败都是访问到了google.cn,说明重定向没有起作用。

**Comment by LLLLLFish** [comment]
我也不知道为啥，对比了一下别人的规则是302我就改成302居然可以了就没有深究

**Comment by LeonSparta** [comment]
嘿嘿嘿，我也是对比了默认的规则发现是302。等等作者吧，不知道会不会回答

**Comment by LLLLLFish** [comment]
更新最新的小火箭2.1.24就会这样

**Comment by h2y** [comment]
已修改，谢谢反馈 :D
