### ISSUE TITLE
请问为什么添加了conf 没有节点出现

### ISSUE THREAD

**Issue by Ukuyu0** [h2y/Shadowrocket-ADBlock-Rules#179]
RT
添加了lz贴出来的各个conf都试了
用的是iPhone SE 12.1.4
shadowrocket

黑名单那个文件里面没有定义proxy 请问是还要自己用别的方式添加么

**Comment by h2y** [comment]
规则决定哪些网站直连，那些网站用代理。节点是节点。
你可以在 https://tangke.space 找到节点
