### ISSUE TITLE
One Drive 连接不正常

### ISSUE THREAD

**Issue by NLasagna** [h2y/Shadowrocket-ADBlock-Rules#180]
我查到规则里有 One Drive 相关的，但是仍然不能正常连接。测试受到校园网的限制，导致我这里有如下几条规则，同时添加才能访问：

DOMAIN-SUFFIX,bcbits.com,PROXY
DOMAIN-SUFFIX,ogma.iad.appboy.com,PROXY
DOMAIN-SUFFIX,odc.officeapps.live.com,PROXY
DOMAIN-SUFFIX,skyapi.live.net,PROXY
DOMAIN-SUFFIX,centralus1.mediap.svc.ms,PROXY
DOMAIN-SUFFIX,fy3ryg.dm.files.1drv.com,PROXY
DOMAIN-SUFFIX,mobile.pipe.aria.microsoft.com,PROXY
DOMAIN-SUFFIX,gate.hockeyapp.net,PROXY
DOMAIN-SUFFIX,skyapi.live.net,PROXY
DOMAIN-SUFFIX,api.onedrive.com,PROXY
DOMAIN-SUFFIX,vortex.data.microsoft.com,PROXY

**Comment by h2y** [comment]
已添加这些规则，谢谢反馈。
