### ISSUE TITLE
如何安装使用

### ISSUE THREAD

**Issue by legendtfc** [h2y/Shadowrocket-ADBlock-Rules#182]
你好，我不会在ipad上安装使用这个小火箭，请问有安装教程吗？

**Comment by crespowang123** [comment]
ios下载shadowrocket，这个是不可以直接用的，需要导入规则，规则可以使用网站https://github.com/h2y/Shadowrocket-ADBlock-Rules/blob/master/readme.md#%E4%BB%A3%E7%90%86%E5%8E%BB%E5%B9%BF%E5%91%8A
  规则导入后，需要导入节点，节点网站可以使用网站https://free-ss.site/ 这个可能需要翻墙才能打开，需要你先借用朋友的或者iOS app里的vpn临时用下那种限流量的，导入后即可使用，自己摸索下，我也是自己摸索的才会的

**Comment by legendtfc** [comment]
感谢！我试着自己摸索了一下，下载到了shadowrocket，然后用了学长给的服务器，就翻出去了。




------------------ 原始邮件 ------------------
发件人: "crespowang123"<notifications@github.com>; 
发送时间: 2019年6月23日(星期天) 中午12:59
收件人: "h2y/Shadowrocket-ADBlock-Rules"<Shadowrocket-ADBlock-Rules@noreply.github.com>; 
抄送: "唐福川"<1023340673@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [h2y/Shadowrocket-ADBlock-Rules] 如何安装使用 (#182)




ios下载shadowrocket，这个是不可以直接用的，需要导入规则，规则可以使用网站https://github.com/h2y/Shadowrocket-ADBlock-Rules/blob/master/readme.md#%E4%BB%A3%E7%90%86%E5%8E%BB%E5%B9%BF%E5%91%8A
 规则导入后，需要导入节点，节点网站可以使用网站https://free-ss.site/ 这个可能需要翻墙才能打开，需要你先借用朋友的或者iOS app里的vpn临时用下那种限流量的，导入后即可使用，自己摸索下，我也是自己摸索的才会的

**Comment by legendtfc** [comment]
突然觉得这个好温暖啊哈哈哈，第一次在网上遇到问题留言还专门发邮件回复的，祝福你啦~




------------------ 原始邮件 ------------------
发件人: "crespowang123"<notifications@github.com>; 
发送时间: 2019年6月23日(星期天) 中午12:59
收件人: "h2y/Shadowrocket-ADBlock-Rules"<Shadowrocket-ADBlock-Rules@noreply.github.com>; 
抄送: "唐福川"<1023340673@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [h2y/Shadowrocket-ADBlock-Rules] 如何安装使用 (#182)




ios下载shadowrocket，这个是不可以直接用的，需要导入规则，规则可以使用网站https://github.com/h2y/Shadowrocket-ADBlock-Rules/blob/master/readme.md#%E4%BB%A3%E7%90%86%E5%8E%BB%E5%B9%BF%E5%91%8A
 规则导入后，需要导入节点，节点网站可以使用网站https://free-ss.site/ 这个可能需要翻墙才能打开，需要你先借用朋友的或者iOS app里的vpn临时用下那种限流量的，导入后即可使用，自己摸索下，我也是自己摸索的才会的
