### ISSUE TITLE
黑名单请添加代理mendeley.com

### ISSUE THREAD

**Issue by godsome** [h2y/Shadowrocket-ADBlock-Rules#183]
mendeley是个开源文献管理器，但云服务器在国外，需要代理

**Comment by sicklefish** [comment]
其实你可以在作者规则上 自己手动添加   这样还比较方便

**Comment by h2y** [comment]
我这里测试了一下，不挂代理是可以上 mendeley 官网的。

**Comment by godsome** [comment]
> 我这里测试了一下，不挂代理是可以上 mendeley 官网的。

上官网不用代理，但是同步文件，不挂代理极其慢，甚至无法同步成功。主要是自己手动添加规则，一更新仓库规则就被覆盖掉了，所以希望能够添加这条规则。

**Comment by aflyingnoob** [comment]
用onedrive同步就行了， mendeley的服务器2G又慢又不好用。

**Comment by h2y** [comment]
已添加此条
