### ISSUE TITLE
手机IOS Shadowrocket场景模式下直连的问题

### ISSUE THREAD

**Issue by ClownTechnology** [h2y/Shadowrocket-ADBlock-Rules#185]
黑名单规则、白名单规则、全局直连+去广告
这三个规则在ios Shadowrocket里使用场景模式的时候会出现以下状况：
因为家里路由已经翻墙，所以使用场景模式设置为连上家里WIFI使用直连，以上三个规则（其他规则没试过）都会导致在路由器已经翻墙的情况下连上路由后无法翻墙（有可能是路由也翻了，手机Shadowrocket也翻了，重复翻墙倒是速度很慢很慢让人误以为翻不了）。
并且在设置过程中我测试使用以上三个规则在路由器停止翻墙后（还是连接已经设置好场景的那个WIFI）还是会翻墙，也就是说没有成功直连路由器，手机还是在翻墙

**Comment by h2y** [comment]
这看起来更像是 Shadowrocket App 的问题？建议你修改下各种设置试试。

**Comment by dyzzc** [comment]
我也这样，路由自己可以翻，但是在shadowrocket场景模式中设置连接该WiFi ssid时直连，结果无法翻墙。关闭shadowrocket就可以翻墙
