### ISSUE TITLE
whatsapp用配置模式无法连接

### ISSUE THREAD

**Issue by z991238** [h2y/Shadowrocket-ADBlock-Rules#189]
为什么whatsapp下用配置模式经常是连接中呢。如果走代理模式就不存在这个问题

**Comment by h2y** [comment]
没有更多的反馈，先关闭了。

**Comment by duckzhouya** [comment]
@z991238 我好像也是，使用proxy模式就可以连接上，但是使用config就不行，你现在还是一直使用proxy模式吗？
@h2y 这个是因为config的whatsapp配置需要修改吗？我用的规则是：https://raw.githubusercontent.com/h2y/Shadowrocket-ADBlock-Rules/master/sr_top500_banlist_ad.conf

**Comment by erichuang1994** [comment]
> @z991238 我好像也是，使用proxy模式就可以连接上，但是使用config就不行，你现在还是一直使用proxy模式吗？
> @h2y 这个是因为config的whatsapp配置需要修改吗？我用的规则是：https://raw.githubusercontent.com/h2y/Shadowrocket-ADBlock-Rules/master/sr_top500_banlist_ad.conf

测试了一下看起来和去广告的规则有关 把规则改成https://raw.githubusercontent.com/h2y/Shadowrocket-ADBlock-Rules/master/sr_cnip.conf 不带上去广告就可以了

**Comment by erichuang1994** [comment]
试试加个DOMAIN-SUFFIX,push-apple.com.akadns.net,proxy
