### ISSUE TITLE
网易新闻app不能用。

### ISSUE THREAD

**Issue by shaozige** [h2y/Shadowrocket-ADBlock-Rules#2]
网易新闻不能用，其他暂时还没发现。。

**Comment by damonzheng** [comment]
貌似g.163.com这个url不能直接reject

**Comment by h2y** [comment]
@shaozige 

现在已经将 g.163.com 移除，在 SR 设置里面重新点下 Use Config，就可以重新下载最新的规则文件了。

**Comment by hilen** [comment]
网易新闻的图片依然不行额
