### ISSUE TITLE
apple news不在黑名单中

### ISSUE THREAD

**Issue by wudimenghuan** [h2y/Shadowrocket-ADBlock-Rules#205]
请添加apple news到黑名单中，白名单的apple.com可能也需要排除apple news，不能直连

v2ex有人写的：

#APPLE NEWS
DOMAIN-SUFFIX,news-events.apple.com,Proxy
DOMAIN-SUFFIX,news-edge.apple.com,Proxy
DOMAIN-SUFFIX,apple.comscoreresearch.com,Proxy
DOMAIN-SUFFIX,play.itunes.apple.com,Proxy
DOMAIN-SUFFIX,play-cdn.itunes-apple.com.akadns.net,Proxy
DOMAIN-SUFFIX,ls.apple.com,Proxy
DOMAIN-SUFFIX,cvws.apple-dns.net,Proxy
DOMAIN-SUFFIX,news.apple-dns.net,Proxy
DOMAIN-SUFFIX,gateway.fe.apple-dns.net,Proxy
DOMAIN-SUFFIX,akamaiedge.net,Proxy
DOMAIN-SUFFIX,gs-loc.apple.com,Proxy
DOMAIN-SUFFIX,bag.itunes.apple.com,Proxy
DOMAIN-SUFFIX,apple.news,Proxy
DOMAIN-SUFFIX,news.iadsdk.apple.com,Proxy

**Comment by h2y** [comment]
已合并此规则，谢谢反馈！
