### ISSUE TITLE
自定义gfwlist自动检查是否为base64编码

### ISSUE THREAD

**Issue by TwilightHome** [h2y/Shadowrocket-ADBlock-Rules#212]
有一些第三方的gfwlist是明文形式的,建议增加一个关闭base64编码检查的开关

**Comment by h2y** [comment]
如果有特殊的要求可以自己修改一下代码，正常情况下使用 <https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt> 就没问题了。
