### ISSUE TITLE
希望能添加一下去除 Google 广告的规则

### ISSUE THREAD

**Issue by hguandl** [h2y/Shadowrocket-ADBlock-Rules#22]
我想使用SR的人都会常常浏览英文网站，我就时常浏览一些境外媒体(比如 BBC)的新闻 App，里面穿插的较多 Google Ads 就非常影响阅读。我查了一下，就自己添加了几个屏蔽的域名关键词，虽然还有广告框，但是绝大部分的广告内容已经不会显示了，希望作者能添加一下类似的规则：
googlesyndicati DOMAIN-KEYWORD REJECT
googlead DOMAIN-KEYWORD REJECT
doubleclick DOMAIN-KEYWORD REJECT
可能这些规则有点过于简单粗暴，如果作者感兴趣希望能完善一下。
最后感谢作者分享出这么简洁好用的配置文件！

**Comment by wangxufire** [comment]
google的广告都要屏蔽。，没人性啊，google账号能设置关注的广告类型，你可以选择不关注任何类型

**Comment by h2y** [comment]
<https://github.com/h2y/Shadowrocket-ADBlock-Rules/commit/499ce5af466e9f762da3c040b804fe799d8d8b23>

已添加相关规则。
谷歌的广告确实是无处不在。
