### ISSUE TITLE
Google amp网页无法访问

### ISSUE THREAD

**Issue by lsabc1** [h2y/Shadowrocket-ADBlock-Rules#237]
在国内外划分和白名单模式下，所有使用Google amp技术的网页都无法访问，显示404错误。奇怪的是在黑名单模式下反而能够访问。全局模式也能正常访问。
![827303C8-79E9-4698-9905-7EE4734F9A7F](https://user-images.githubusercontent.com/11485587/76055624-1e456000-5faf-11ea-83ad-bb8931298861.png)

**Comment by xPixv** [comment]
https://www.v2ex.com/t/332817

Fixed in #243

**Comment by h2y** [comment]
感谢 xPixv ~
