### ISSUE TITLE
某行错误

### ISSUE THREAD

**Issue by iOSteveReagan** [h2y/Shadowrocket-ADBlock-Rules#25]
在某行中是：DOMAIN-SUFFIX,91porn.com.Proxy
应该修改成：DOMAIN-SUFFIX,91porn.com,Proxy
com 后面是逗号不是点，希望能更新好。
还有一个问题就是 IP 规则应该放在最后，而不是倒二个，谢谢。
![img_2609](https://cloud.githubusercontent.com/assets/18232831/26042624/857fe926-3969-11e7-80c9-d968722aa4e1.PNG)

**Comment by h2y** [comment]
谢谢反馈
😄
