### ISSUE TITLE
请添加AcFun进入直连白名单

### ISSUE THREAD

**Issue by Lablace** [h2y/Shadowrocket-ADBlock-Rules#272]
看了一下最新的白名单，里面有B站但没有A站，这怎么能行呢。请添加如下两个子域名：
DOMAIN-SUFFIX,acfun.cn,DIRECT
DOMAIN-SUFFIX,aixifan.cn,DIRECT
上面那个是主站地址，后面那个是cdn和数据库。
小破站也在一天天变好哦。

**Comment by Veckian** [comment]
自己不就可以添加了吗

**Comment by Lablace** [comment]
> 自己不就可以添加了吗

嗯，是的。但是直连白名单的话，作为一个国内视频网站应该被加进去，毕竟它现在日访问量没有以前那么低了。既然是O(n)的复杂度，加上这两条的影响应该不大。

**Comment by Lablace** [comment]
因为作者停更了，所以关闭此issue。
