### ISSUE TITLE
Shadowrocket“全局路由”模式选择问题

### ISSUE THREAD

**Issue by wujin941005** [h2y/Shadowrocket-ADBlock-Rules#30]
如果我的理解正确的话“黑名单过滤 + 广告”和“手工规则”应该是选择“配置”吧，因为他们都是属于pac里写着哪些proxy而默认网络是直连，而“白名单过滤 + 广告”应该是“代理”，等于是先全局代理然后根据pac再排除直连网站。谢谢！

**Comment by wujin941005** [comment]
我的疑问应该解决了，应该都是选择“配置”。三个pac里都有*.final，及剩下所有网站，黑名单则是final Direct，而白名单final为Proxy

**Comment by h2y** [comment]
是的，选择“配置”，仅在需要全局代理的时候选择“代理”
