### ISSUE TITLE
没有域名转跳啊，ios中国地区默认设置为中国的话就不能使用谷歌作为浏览器默认的搜索引擎了！

### ISSUE THREAD

**Issue by artcaster** [h2y/Shadowrocket-ADBlock-Rules#31]
没有域名转跳啊，ios中国地区默认设置为中国的话就不能使用谷歌作为浏览器默认的搜索引擎了！希望大大能加入，google.cn转跳google.com

**Comment by h2y** [comment]
<https://github.com/h2y/Shadowrocket-ADBlock-Rules/commit/71a7fd4db1d113c795fb42604e577245a37a3569>

已修复。

**Comment by artcaster** [comment]
这么快，谢谢大大

发自我的 iPhone
