### ISSUE TITLE
白名单的配置文件中不应该有github

### ISSUE THREAD

**Issue by lizhaode** [h2y/Shadowrocket-ADBlock-Rules#36]
我的理由是这样的：

在联通、电信这种一级运营商中，github.com和github.io是基本上可以正常访问，且速度还不错

但是在 移动宽带 ，我个人的经验是 一些时候可以正常访问，但是有很多时候是速度非常慢，甚至有的时候干脆就不能访问

在长城宽带、宽带通、广电 这种宽带的分销商中，大多数时候，github都是没法访问的

所以我建议在白名单中去掉github，这样可以适配更多运营商的用户

**Comment by h2y** [comment]
再看看有没有更多人反馈这个问题吧，暂时不打算修改。

我通过 <https://www.17ce.com/> 检测，表明 github.com 在各 ISP 下基本都是可以访问的，只是速度不快。

github 需要代理的是少数网民，如果统一为代理连接的话，恐怕会造成更多的疑问。
