### ISSUE TITLE
反馈：开启了“手工规则”，Appstore不能更新软件

### ISSUE THREAD

**Issue by fun5rt** [h2y/Shadowrocket-ADBlock-Rules#37]
我用Shadowrocket软件，开启了“手工规则”，软件和规则都是最新版，然后通过Appstore就不能更新、下载任何软件了。
关闭VPN连接之后可以了，请问这个是什么原因呢？

**Comment by h2y** [comment]
请使用 sr_top500_banlist_ad.conf 代替 手工规则，以后手工规则会越来越少地维护了。
