### ISSUE TITLE
QQ空间 图片显示不出来

### ISSUE THREAD

**Issue by yuchuanfeng** [h2y/Shadowrocket-ADBlock-Rules#4]

**Comment by h2y** [comment]
经测试没有问题，8 月 13 号 <https://github.com/h2y/Shadowrocket-ADBlock-Rules/commit/7d0ed9e9bfd077ed645a322cc3d7c3b99b05e1cc> 更新了 QZone 不能正常使用的问题。

但 SR 不会自动更新导入的规则，你可以点击重新下载规则看看。

**Comment by yuchuanfeng** [comment]
好的  我更新了下 可以显示了 非常感谢
