### ISSUE TITLE
Unable to watch video

### ISSUE THREAD

**Issue by iam3ddy** [h2y/Shadowrocket-ADBlock-Rules#41]
Using your sr_adb.conf, i'm unable to watch live streams on toggle.sg
geo-blocked by toggle

**Comment by h2y** [comment]
<http://video.toggle.sg/en/video/channels/suria/237652>

i test this page, and i can't watch the video in all of ways.

please commit a link which can show in normal way but blocked by my rule.

**Comment by iam3ddy** [comment]
i was using a singapore server.
using shadowrocket, when i set GLOBAL mode or using default.conf
No issue watching the live channels.

I'm not sure which of your rules set "DIRECT" which causes the geo-block
their streaming source was from akamaihd.net
but i did not find them in your rules.

still puzzled what's causing it

**Comment by h2y** [comment]
it seems that the service can't use in some area, have nothing to do with this rule.
