### ISSUE TITLE
Telegram （ios+shadowrocket+ssr） 使用（黑名单+去广告无效）

### ISSUE THREAD

**Issue by freebumblebee** [h2y/Shadowrocket-ADBlock-Rules#43]
应用sr_top500_banlist_ad.conf 无法连接
应用sr_top500_banlist.conf 可连接，可正常使用 

规则版本均为8/13

感谢你编写规则，使用反馈如上

**Comment by h2y** [comment]
谢谢反馈，我没有用telegram，所以希望能继续反馈一下被错误reject 的地址，使用app的日志功能即可看到。

**Comment by freebumblebee** [comment]
此问题已在8/22的版本后修复了，banlist_ad也可以连上telegram了，目前用9/1的版本也没有发现问题。
感谢h2y。我关issues了。
