### ISSUE TITLE
代理规则的建议

### ISSUE THREAD

**Issue by lt-gen2er** [h2y/Shadowrocket-ADBlock-Rules#48]
部分站点可能有在不同地区会连不同地区的服务器，比方说amazon，hp，dell等等，规则里都是直连，但是访问其境外站点的话不走代理速度还是会慢一些，建议后面加上国内后缀的直连，其他走代理。
另外就是有些日本站会检测是不是本国ip，比方说开车的dmm，规则是直连，上是上的去，但是浏览不了内容，我觉得可以把这些日本站删掉，换成geoip，检测到日本自动走日本线路。

**Comment by h2y** [comment]
大多数网站是没有这样区别对待的，现在是如果出现了规则不正确的情况，根据大家的反馈进行手动的修改。

**Comment by h2y** [comment]
由于使用本规则的用户并不都是日本代理，如果有需求可以自己动手哦。
