### ISSUE TITLE
使用 ping 判断网站是否被墙

### ISSUE THREAD

**Issue by h2y** [h2y/Shadowrocket-ADBlock-Rules#53]
生成规则文件时，目前使用的是 GET 判断，但实际上使用 ping 会更快而且更加准确？

**Comment by truebit** [comment]
http GET 更准吧。
ping也有可能能通，但是访问不了的。
想要快的话，可以用gevent并发来实现。或者用python3的asyncio

**Comment by h2y** [comment]
应该是这样的，那就不改了。
