### ISSUE TITLE
台灣香港澳門常用網站

### ISSUE THREAD

**Issue by Enterpr1se** [h2y/Shadowrocket-ADBlock-Rules#54]
ptt.cc
mingpaocanada.com
mingpao.com
appledaily.com
appledaily.tw
nextmag.com.tw
nextdigital.com.hk
nextdigital.com
thestandnews.com
hk01.com

**Comment by h2y** [comment]
将在 #57 之后解决不能访问的问题。

**Comment by h2y** [comment]
已添加
