### ISSUE TITLE
请教大神，用url重写屏蔽特定地址广告失败，其他url重写都能生效唯独这条不行

### ISSUE THREAD

**Issue by fhruoefhuof** [h2y/Shadowrocket-ADBlock-Rules#59]
请教大神我想屏蔽京东金融app的某条启动广告，地址如下
https://img12.360buyimg.com/jrpmobile/jfs/t11152/221/2398842244/265299/9e9c4da4/5a17838dN98edd21f.jpg?width=1242&height=1854

我用shadowrocket的url重写功能写了很多条（如下），但这个地址的图片还是能打开没有被屏蔽，其他app的广告都能用url重写屏蔽，可就是这条广告怎么写都屏蔽不了，请教该怎么写才能屏蔽此广告

^https://img12.360buyimg.com/jrpmobile/jfs/t11152/221/2398842244/265299/9e9c4da4/5a17838dN98edd21f.jpg?width=1242&height=1854 reject

^(http|https)://img12.360buyimg.com/jrpmobile/jfs/t11152/221/2398842244/265299/9e9c4da4/5a17838dN98edd21f.jpg reject

^https://img12.360buyimg.com/jrpmobile/jfs/t11152/221/2398842244/265299/9e9c4da4/5a17838dN98edd21f.jpg reject

^https://img12.360buyimg.com reject 最后哪怕我都这样写url重写了，还是不行啊

PS：此app内容图片和启动广告共用img12.360buyimg.com这个域名，虽然规则能直接屏蔽掉整个域名但不是我所期望的，所以只能用url重写屏蔽此广告

**Comment by fhruoefhuof** [comment]
第一次用github，不知道发在这里合不合适，真是打扰了

**Comment by h2y** [comment]
`^https://img12.360buyimg.com/jrpmobile/jfs/t11152/221/2398842244/265299/9e9c4da4/5a17838dN98edd21f.*$ reject`

试试这样，正则表达式中 . 和 ? 都是关键字，出现在 url 中需要用 \. 这样代替。

**Comment by fhruoefhuof** [comment]
找到问题了，是https解密里没有添加此域名，再按照你的建议写了规则就能屏蔽了，谢谢耐心回复
