### ISSUE TITLE
请问怎么把文件放在 raw.githubusercontent.com上的呢? 求教

### ISSUE THREAD

**Issue by yangxiaoge** [h2y/Shadowrocket-ADBlock-Rules#6]

**Comment by h2y** [comment]
把文件上传到 git 仓库后，进入 <https://github.com/h2y/Shadowrocket-ADBlock-Rules/blob/master/sr_adb.conf> 这样的页面。

再点击那个 `RAW` 按钮就会进入这个文件的源文件地址。

**Comment by tedyyu** [comment]
The button is now called Download.
