### ISSUE TITLE
建議增加一種模式：國內ip直連，境外走代理

### ISSUE THREAD

**Issue by ntgeralt** [h2y/Shadowrocket-ADBlock-Rules#69]
這建議在經常訪問香港和台灣電視內容時候遇到：直連是允許的，但速度很慢，對大陸運營商非常不友好；走代理則訪問飛快。

**Comment by wao1201** [comment]
+1

**Comment by h2y** [comment]
👍 
已添加
![default](https://user-images.githubusercontent.com/12909077/35178930-22161424-fdcb-11e7-8c4f-ae85d0b6ed93.png)
![1](https://user-images.githubusercontent.com/12909077/35178931-22627c24-fdcb-11e7-8d99-d5cc5f529d30.png)
