### ISSUE TITLE
建议增加gfwlist完整版黑名单

### ISSUE THREAD

**Issue by shuanglengyunji** [h2y/Shadowrocket-ADBlock-Rules#71]
完全版的gfwlist还是有些作用的

**Comment by f2sky** [comment]
这个规则的特色就是轻量化的 top500 列表，然后你们又要求退回去包含完整的……
那你们可以直接使用其它提供完整版列表的规则啊。

目前作者提供的规则能够满足绝大部分使用需求，没有必要为了大量冷门网站提供完整的 GFW 屏蔽列表，保持轻量和高效的特色。

**Comment by shuanglengyunji** [comment]
其实感觉这个轻量化版本挺不错，只要代理服务器够给力，白名单模式远好于黑名单。
关于添加完整黑名单，我觉得是出于大家对这个项目的信任，网上类似的项目很多，能够放心使用的其实没几个。大家喜欢这个项目，才会进一步提出自己的需求的。

在 2018年5月6日 上午8:04，Leslie <notifications@github.com>写道：

**Comment by h2y** [comment]
最新版已使用完整版 GFWList，完美转译最新版本，欢迎大家使用。

以前我也认为 top500 的黑名单轻量规则足够，但事实证明遗漏的太多（当然白名单使用 top500 生成是很好的，不会变），黑名单还是得要用 GFWList。

以前轻量版本的 黑名单+广告规则 保留在 `sr_adb.conf` 文件中，并按照以前的规则由爬虫继续定期更新。
