### ISSUE TITLE
自己整理的列表，如果有效，还请添加到相关list中

### ISSUE THREAD

**Issue by trotack** [h2y/Shadowrocket-ADBlock-Rules#73]
DOMAIN-SUFFIX,pingma.qq.com,REJECT
DOMAIN-KEYWORD,cloudmobi,REJECT
DOMAIN-SUFFIX,static.ws.126.net,REJECT
DOMAIN-SUFFIX,sp0.baidu.com,REJECT
DOMAIN-SUFFIX,img3.cache.netease.com,REJECT
DOMAIN-SUFFIX,zyz.91friend.com,REJECT
DOMAIN-SUFFIX,zyz.mipujia.com,REJECT
DOMAIN-SUFFIX,mixer.sina.cn,REJECT
DOMAIN-SUFFIX,images.pagechoice.net,REJECT
DOMAIN-SUFFIX,sa.sina.cn,REJECT
DOMAIN-SUFFIX,pfp.sina.net,REJECT
DOMAIN-SUFFIX,artofclick.com,REJECT
DOMAIN-SUFFIX,revmobads.com,REJECT
DOMAIN-SUFFIX,revmob.com,REJECT
DOMAIN-SUFFIX,clk.taptica.com,REJECT
DOMAIN-SUFFIX,saxn.sina.com.cn,REJECT
DOMAIN-SUFFIX,100669.com,REJECT
DOMAIN-SUFFIX,wx.go189.cn,REJECT
DOMAIN-SUFFIX,ymtrack6.co,REJECT
DOMAIN-SUFFIX,go2speed.com,REJECT
DOMAIN-SUFFIX,lenzmx.com,REJECT
DOMAIN-SUFFIX,gowadogo.com,REJECT
DOMAIN-SUFFIX,sumatoad.com,REJECT
DOMAIN-SUFFIX,appflood.com,REJECT
DOMAIN-SUFFIX,ymtracking.com,REJECT
DOMAIN-SUFFIX,pubnative.net,REJECT
DOMAIN-SUFFIX,go2cloud.com,REJECT
DOMAIN-SUFFIX,appsflyer.com,REJECT
DOMAIN-SUFFIX,vision-vision.com,REJECT
DOMAIN-SUFFIX,cnzz.com,REJECT
DOMAIN-SUFFIX,ad.12306.cn,REJECT
DOMAIN-KEYWORD,appnext,REJECT
DOMAIN-SUFFIX,ads.mopub.com,REJECT
DOMAIN-SUFFIX,ads.nexage.com,REJECT
DOMAIN-SUFFIX,ads.aerserv.com,REJECT

**Comment by h2y** [comment]
谢谢提交，但本规则关于广告的部分是自动获取乘风规则、ChinaList 并且转换，所以广告的提交推荐提交到上游。

@xinggsf [xinggsf/Adblock-Plus-Rule](https://github.com/xinggsf/Adblock-Plus-Rule)
