### ISSUE TITLE
“黑名单+过滤广告”+“白名单+过滤广告”，广告部分的规则是不是重复？

### ISSUE THREAD

**Issue by Puxuan-H** [h2y/Shadowrocket-ADBlock-Rules#78]
我在Quan里把两个规则都加入了（即“黑名单+过滤广告”+“白名单+过滤广告”），是不是不太合理？
是否应该是“黑名单+过滤广告”+“白名单”即可？

感谢

**Comment by h2y** [comment]
这里的每一个规则都是单独使用的，使用其中一个即可~
