### ISSUE TITLE
请问如何启动直连去广告？

### ISSUE THREAD

**Issue by jijiucheng** [h2y/Shadowrocket-ADBlock-Rules#81]
我在 Shadowrocket 已经配置了，也选择了直连，但是发现没有任何作用

**Comment by wao1201** [comment]
这已经是规则了，你要在火箭里选择此规则应用，“直连”在这里指的是规则里的直连，不知火箭里设置直连，那样的话等于不启用规则

**Comment by jijiucheng** [comment]
我是在 Shadowrocket 的配置里配置好之后，点击了“使用配置”，因为没有在配置栏里找到“直连”，我就在首页里的连接方式设置直连，然后启动连接，然后再启用其他的软件，发现没有任何过滤广告的功能

**Comment by wao1201** [comment]
Global Routing 里选择 Config 才会启用你下载的规则

**Comment by h2y** [comment]
你选择了直连或者代理，那就意味着忽略规则。
请选择“规则”
