### ISSUE TITLE
3.8日最新视频广告效果测试反馈

### ISSUE THREAD

**Issue by seven76six** [h2y/Shadowrocket-ADBlock-Rules#84]
系统IOS11.3，视频软件均为2018年3月8日最新版
使用规则：黑名单过滤 + 广告
爱奇艺 V9.1.0
大部分视频广告屏蔽了 开屏没去除
底部导航除了第一个首页能显示，底部其他项目均显示加载失败了
只能通过搜索来看到其他电影
播放个别视频提示出错啦
开屏可以不去除，恢复底部几个选项页面内容即可，主要是去视频前广告
视频下面评论和杂七杂八的可以保持屏蔽，以免不能正常去除视频广告
最起码现在想看什么电影进去搜索了看，没有任何广告，很清爽

腾讯视频 6.0.3 B21350
太完美，低调使用
秒进软件，秒进视频，无误杀

搜狐视频 V6,9,2
有开屏广告
无视频广告
无误杀

乐视视频V7.10
无效果
3秒开屏广告
75秒视频广告
乐视就不用太在意了，没有资源优势

PP视频 V7.3.9
完美
无开屏广告
无视频广告

优酷 V7.1.8
无效果，该有的还是有

**Comment by h2y** [comment]
给力给力，测试辛苦了。
合并到 #40 啦

**Comment by seven76six** [comment]
你也辛苦了！
