### ISSUE TITLE
3月8日版YouTube软件视频首图不显示修复规则和google广告规则

### ISSUE THREAD

**Issue by seven76six** [h2y/Shadowrocket-ADBlock-Rules#85]
下面这个地址不能走直连了，被墙了，所以YouTube APP最新版的视频首图不能读取。
加一下这个规则
DOMAIN-SUFFIX,yt3.ggpht.com,PROXY

下面是Google可以BAN掉的地址，这样www.speedtest.net的Google广告也可以去除。

DOMAIN-SUFFIX,www-google-analytics.l.google.com,REJECT
DOMAIN-SUFFIX,ssl-google-analytics.l.google.com,REJECT
DOMAIN-SUFFIX,partnerad.l.google.com,REJECT
DOMAIN-SUFFIX,pagead.l.google.com,REJECT
DOMAIN-SUFFIX,pagead.google.com,REJECT
DOMAIN-SUFFIX,pagead-tpc.l.google.com,REJECT
DOMAIN-SUFFIX,mobileads.google.com,REJECT
DOMAIN-SUFFIX,afd.l.google.com,REJECT
DOMAIN-SUFFIX,ads.google.com,REJECT

下面地址肯定是是优酷必ban的
DOMAIN-SUFFIX,static.lstat.youku.com,REJECT
DOMAIN-SUFFIX,static.youku.com,REJECT
DOMAIN-SUFFIX,val.atm.youku.com,REJECT
DOMAIN-SUFFIX,3g.youku.com,REJECT

有错的楼下吼一下

**Comment by h2y** [comment]
谢谢反馈，已经完成添加。
优酷的域名没有添加，因为添加了也是无法过滤广告的。
