### ISSUE TITLE
回国规则

### ISSUE THREAD

**Issue by h2y** [h2y/Shadowrocket-ADBlock-Rules#86]
需要：一个国内 ip 都走代理, 而国外 ip 不走代理的规则

**Comment by brendan0524** [comment]
同样需要这个规则  麻烦了

**Comment by jackiejtr** [comment]
同求

**Comment by h2y** [comment]
已添加回国规则。

最近比较忙，更新迟了~ 

顺便安利一下我使用的糖客 vpn 服务（<http://tangke.party/register?aff=56>），价格便宜速度快，支持回国节点。
