### ISSUE TITLE
可能我太菜了，请问SSR怎么用这个规则啊？

### ISSUE THREAD

**Issue by lijxse** [h2y/Shadowrocket-ADBlock-Rules#87]
conf贴到PAC里不好使啊。
ios里的小火箭直接扫码就能用了。还有WIN和mac的SSR不知道怎么用这个。

**Comment by h2y** [comment]
这个规则就是给小火箭用的。
电脑端建议使用默认规则，再配合浏览器上面的过滤广告插件，就可以了。
