### ISSUE TITLE
开着shadowrocket从appstore下载或者更新app老是失败，每次更新app都要关闭小火箭好麻烦啊

### ISSUE THREAD

**Issue by fhruoefhuof** [h2y/Shadowrocket-ADBlock-Rules#94]
开着shadowrocket从appstore下载或者更新app老是失败，每次更新app都要关闭小火箭好麻烦啊

是哪里没设置好吗

**Comment by h2y** [comment]
我也是这个情况，App store间歇性不好用。
不过使用其他规则貌似也是这个情况。

**Comment by h2y** [comment]
这个问题不好复现，有的时候开着规则又是可以正常下载的。
这问题有待进一步讨论。
