### ISSUE TITLE
SR_cnip.conf 不能连接 facebook message

### ISSUE THREAD

**Issue by vv1001** [h2y/Shadowrocket-ADBlock-Rules#98]
使用SR_cnip.conf 文件，不能连接 facebook message，请检查。

**Comment by h2y** [comment]
<https://raw.githubusercontent.com/h2y/Shadowrocket-ADBlock-Rules/master/sr_cnip.conf>

CNIP 规则的内容是很简单的几行：调用 SR 本身的 geoip 模块，对国内直连，对国外代理。
如果使用该规则出现的错误，需要向 SR 反馈，因为这并不是规则不完善导致的。

**Comment by h2y** [comment]
除非一种情况，是 Facebook 使用的是大陆的服务器。

**Comment by vv1001** [comment]
但是，我使用shadowrockect 自带的默认配置文件，就没有问题。

**Comment by vv1001** [comment]
使用本网站的配置，我也多次测试，有时候能连上，有时候不行，昨天晚上是可以的，刚测试就不行了

**Comment by vv1001** [comment]
刚测试又可以了

**Comment by h2y** [comment]
等待更多人反馈该问题。
