### ISSUE TITLE
广告屏蔽合并请求

### ISSUE THREAD

**Issue by id7368** [h2y/Shadowrocket-ADBlock-Rules#99]
#以下为杭州公交APP的广告调用地址，含京东广告
DOMAIN-SUFFIX,et.w.inmobi.cn,REJECT
DOMAIN-SUFFIX,im-x.jd.com,REJECT
DOMAIN-SUFFIX,ad.ipadview.com,REJECT

#以下为某些不可描述网站加载的乱七八糟广告
DOMAIN-SUFFIX,sfd.maizhenai.cn,REJECT
DOMAIN-SUFFIX,cl21iq.paomifen.cn,REJECT
DOMAIN-SUFFIX,ll.songlaoban.cn,REJECT
DOMAIN-SUFFIX,img.09mk.cn,REJECT
DOMAIN-SUFFIX,hepengshan.cn,REJECT
DOMAIN-SUFFIX,pp.images.harmony.epsilon.com,REJECT
DOMAIN-SUFFIX,gum.criteo.com,REJECT
DOMAIN-SUFFIX,www.storygize.net,REJECT
DOMAIN-SUFFIX,pxl.connexity.net,REJECT
DOMAIN-SUFFIX,i.liadm.com,REJECT
DOMAIN-SUFFIX,aa.agkn.com,REJECT
DOMAIN-SUFFIX,load77.exelator.com,REJECT
DOMAIN-SUFFIX,stags.bluekai.com,REJECT
DOMAIN-SUFFIX,d.agkn.com,REJECT
DOMAIN-SUFFIX,sds.amaoshe.cn,REJECT
DOMAIN-SUFFIX,dd.yeshoutuan.cn,REJECT
DOMAIN-SUFFIX,h.muxq8.cn,REJECT
DOMAIN-SUFFIX,ls.huanshawang.cn,REJECT
DOMAIN-SUFFIX,e.v85968.cn,REJECT
DOMAIN-SUFFIX,co.dingyuanyao.cn,REJECT
DOMAIN-SUFFIX,dd.ythongsheng.cn,REJECT
DOMAIN-SUFFIX,lolo.viwuue.cn,REJECT
DOMAIN-SUFFIX,bp.xkhejx.cn,REJECT

#以下为广告联盟
DOMAIN-SUFFIX,taboola.com,REJECT
DOMAIN-SUFFIX,trc.taboola.com,REJECT
DOMAIN-SUFFIX,union.bokecc.com,REJECT

**Comment by id7368** [comment]
#付呗收款码支付后跳转到的广告地址（支付宝内）
DOMAIN-SUFFIX,*.tuisnake.com,REJECT
DOMAIN-SUFFIX,*.duiba.com.cn,REJECT
DOMAIN-SUFFIX,*.tarollcake.*,REJECT
DOMAIN-SUFFIX,*.dui88.com,REJECT

#网易云音乐跟踪
DOMAIN-SUFFIX,*.nosdn.127.net,REJECT
DOMAIN-SUFFIX,iadmat.nosdn.127.net,REJECT

#喜马拉雅跟踪和广告
DOMAIN-SUFFIX,location.ximalaya.com,REJECT
DOMAIN-SUFFIX,adse.ximalaya.com,REJECT
DOMAIN-SUFFIX,xdcs-collector.ximalaya.com,REJECT
DOMAIN-SUFFIX,xdcs-collector.ximalaya.com,REJECT
DOMAIN-SUFFIX,xdcs-collector.ximalaya.com,REJECT

#部分优酷视频贴片广告
DOMAIN-SUFFIX,cws-cctv.conviva.com,DIRECT

#友盟分享SDK追踪
DOMAIN-SUFFIX,*.umsns.*,REJECT

#极光推送SDK
DOMAIN-SUFFIX,*.jpush.*,REJECT

#神策数据 追踪用户操作行为
USER-AGENT,SensorsAnalytics*,REJECT

#广告联盟
DOMAIN-SUFFIX,*.inmobi.cn,REJECT
DOMAIN-SUFFIX,*.criteo.com,REJECT

#申请更新规则，以下广告域名子域名此前提交，现更新为通配符(不可描述网站的)
DOMAIN-SUFFIX,*.maizhenai.cn,REJECT
DOMAIN-SUFFIX,*.paomifen.cn,REJECT
DOMAIN-SUFFIX,*.songlaoban.cn,REJECT
DOMAIN-SUFFIX,*.09mk.cn,REJECT
DOMAIN-SUFFIX,*.hepengshan.cn,REJECT
DOMAIN-SUFFIX,*.epsilon.com,REJECT
DOMAIN-SUFFIX,*.storygize.net,REJECT
DOMAIN-SUFFIX,*.connexity.net,REJECT
DOMAIN-SUFFIX,*.liadm.com,REJECT
DOMAIN-SUFFIX,*.agkn.com,REJECT
DOMAIN-SUFFIX,*.exelator.com,REJECT
DOMAIN-SUFFIX,dualstack.adsame-1421766300.ap-southeast-1.elb.amazonaws.com,REJECT
DOMAIN-SUFFIX,*.amaoshe.cn,REJECT
DOMAIN-SUFFIX,*.yeshoutuan.cn,REJECT
DOMAIN-SUFFIX,*.muxq8.cn,REJECT
DOMAIN-SUFFIX,*.huanshawang.cn,REJECT
DOMAIN-SUFFIX,*.v85968.cn,REJECT

**Comment by h2y** [comment]
请问这些规则的来源是哪，会不会存在误杀？

**Comment by id7368** [comment]
全部都是我自己使用发现广告用来屏蔽的，手工整理，误杀应该是不会的。

**Comment by h2y** [comment]
好的，谢谢反馈。下一次更新时我会合并。

**Comment by id7368** [comment]
不好意思有错误，这一条请不要添加：DOMAIN-SUFFIX,.tarollcake.,REJECT

这是付呗跳转的广告页，屏蔽tarollcake关键词可能会让页面样式表错误无法付款，刚刚才发现，抱歉

**Comment by h2y** [comment]
已合并
